name: Auto Approve and Merge PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Validate PR
      run: |
        validate_single_md_file() {
          local file_count=$1
          if [[ $file_count -ne 1 ]]; then
            echo "ERROR: There should be exactly one .md file added or modified in the community/ directory."
            exit 1
          fi
        }
        
        validate_filename_matches_github_actor() {
          local file_basename=$1
          local github_actor=$2
          if [[ $file_basename != "$github_actor" ]]; then
            echo "ERROR: The .md file name '$file_basename' does not match the GitHub username '$github_actor'."
            exit 1
          fi
        }
        
        # Obtenha o nome do arquivo .md adicionado ou modificado na pasta community.
        FILE_NAME=$(git diff --name-only origin/main..HEAD | grep '^community/.*\.md$')
        FILE_BASENAME=$(basename $FILE_NAME .md)
        
        # Verifica se há apenas um arquivo .md adicionado ou modificado na pasta community.
        FILE_COUNT=$(echo $FILE_NAME | wc -l)
        
        # Debugging: Vamos imprimir os valores e ver o que está sendo capturado
        echo "DEBUG: FILE_NAME = $FILE_NAME"
        echo "DEBUG: FILE_BASENAME = $FILE_BASENAME"
        echo "DEBUG: GITHUB ACTOR = ${{ github.actor }}"
        
        validate_single_md_file $FILE_COUNT
        validate_filename_matches_github_actor $FILE_BASENAME ${{ github.actor }}

    - name: Post Comment if Validation Fails
      if: failure()
      run: |
        echo "Ei! Parece que algo não deu certo com o seu PR. Ele deve conter apenas um arquivo .md na pasta 'community/', e o nome desse arquivo deve ser o mesmo que o seu nome de usuário no GitHub. Dê uma olhada nas instruções no README.md e no CONTRIBUTE.md para acertar. Assim que fizer as correções, atualize o PR para que possamos avaliá-lo novamente. Se continuar com problemas, infelizmente a revisão será manual e pode demorar um pouquinho. Valeu pela contribuição 👊😉" > message.txt
        gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Approve PR
      uses: hmarr/auto-approve-action@v2.1.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        
    - name: Merge PR
      uses: pascalgn/automerge-action@v0.13.1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_COMMIT_MESSAGE: "automatic"
        MERGE_METHOD: "squash"
        
    - name: Post Comment for Approved and Merged PRs
      if: success()
      run: |
        echo "E aí! Seu PR com o arquivo .md na pasta 'community/' está perfeito e já foi aprovado! Muito obrigado por se juntar à comunidade 🚀" > message.txt
        gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
