name: Auto Approve and Merge PRs

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code from PR (Safe Checkout)
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Validate PR
      run: |
        AUTHOR_NAME="${{ github.actor }}"
        FILE_PATH="community/$AUTHOR_NAME.md"
        
        if [[ ! -f $FILE_PATH ]]; then
            echo "ERROR: Expected a file at $FILE_PATH, but it doesn't exist."
            exit 1
        fi
        
    - name: Post Comment if Validation Fails
      if: failure()
      run: |
        echo "Ei!? Parece que algo não deu certo com o seu PR. Ele deve conter apenas um arquivo `.md` na pasta `community/` e o nome desse arquivo deve ser o mesmo que o seu nome de usuário no GitHub (atenção, a verificação é sensível a maiúsculas e minúsculas!). Dê uma olhada nas instruções no README.md e no CONTRIBUTE.md para acertar. Assim que fizer as correções, atualize o PR para que possamos avaliá-lo novamente. Se continuar com problemas, infelizmente a revisão será manual e pode demorar um pouquinho. Valeu pela contribuição 👊😉" > message.txt
        gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Approve and Comment PR
      if: success()
      run: |
        echo "E aí! Seu PR com o arquivo `.md` na pasta `community/` foi aprovado com sucesso! Obrigado por fazer parte da nossa comunidade 🚀" > message.txt
        gh pr comment ${{ github.event.pull_request.number }} --body-file=message.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge PR
      uses: "pascalgn/automerge-action@v0.15.6"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
